config/routes.rb
Rails.application.routes.draw do
  resources :sell_games
  resources :charges
  devise_for :users
  root to: "pages#index"
  get 'pages/index' => 'pages#index'
  get 'search' => 'sell_games#search'
  get 'mygames' => 'sell_games#mygames'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
     else
         can :manage, SellGame, user_id: user.id
         can :read, :all
      end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sell_game.rb
class SellGame < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sell_games
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
        protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
    end
    
    def create
      # Amount in cents
      @amount = 500
    
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })
    
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @amount,
        description: 'Rails Stripe customer',
        currency: 'aud',
      })
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sell_games_controller.rb
class SellGamesController < ApplicationController
  load_and_authorize_resource
  before_action :set_sell_game, only: [:show, :edit, :update, :destroy]

  # GET /sell_games
  # GET /sell_games.json
  def _index
    @sell_games = SellGame.all
  end

  def search 
    @sell_games = SellGame.where("title LIKE ?", "%" + params[:q] + "%")
  end

  def mygames
    @sell_games = current_user.sell_games.all  
  end

  # GET /sell_games/1
  # GET /sell_games/1.json
  def show
    session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
            name: @sell_game.title,
            description: @sell_game.description,
            amount: (@sell_game.price.to_i) * 100,
            currency: 'aud',
            quantity: 1,
        }],
        payment_intent_data: {
            metadata: {
                event_id: @sell_game.id
            }
        },
        success_url: "#{root_url}payments/success?sell_gametId=#{@sell_game.id}",
        cancel_url: "#{root_url}sell_games"
    )
    @session_id = session.id
  end

  # GET /sell_games/new
  def new
    @sell_game = SellGame.new
  end

  # GET /sell_games/1/edit
  def edit
  end

  # POST /sell_games
  # POST /sell_games.json
  def create
    @sell_game = SellGame.new(sell_game_params)
    @sell_game.user_id = current_user.id
    respond_to do |format|
      if @sell_game.save
        format.html { redirect_to @sell_game, notice: 'Sell game was successfully created.' }
        format.json { render :show, status: :created, location: @sell_game }
      else
        format.html { render :new }
        format.json { render json: @sell_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sell_games/1
  # PATCH/PUT /sell_games/1.json
  def update
    respond_to do |format|
      if @sell_game.update(sell_game_params)
        format.html { redirect_to @sell_game, notice: 'Sell game was successfully updated.' }
        format.json { render :show, status: :ok, location: @sell_game }
      else
        format.html { render :edit }
        format.json { render json: @sell_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sell_games/1
  # DELETE /sell_games/1.json
  def destroy
    @sell_game.destroy
    respond_to do |format|
      format.html { redirect_to sell_games_url, notice: 'Sell game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sell_game
      @sell_game = SellGame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sell_game_params
      params.fetch(:sell_game, :picture)
      params.require(:sell_game).permit(:title, :price, :description, :user_id, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sell_games_helper.rb
module SellGamesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/index.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameTrade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://blogfonts.com/css/aWQ9ODEwNCZzdWI9MTA0JmM9diZ0dGY9dmFyaWFuZS1zY3JpcHQucmVndWxhci50dGYmbj12YXJpYW5lLXNjcmlwdC1yZWd1bGFy/Variane Script Regular.ttf" rel="stylesheet" type="text/css"/>
</head>
<body id="indexbody">
<%= render "devise/shared/navbar" %>
<br>
<br>
<%= image_tag "cover.png", id: "coverimg"%>
<h3>Welcome to GameTrade! Start a search for a new game below</h3>
<div class="searchdiv">
<form class="example" action="/search" id="searchbar">
  <input type="text" placeholder="Search.." name="q" aria-label="Search">
  <button type="submit"><i class="fa fa-search"></i></button>
</form>
</div>
</body>

app/views/sell_games/_form.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://blogfonts.com/css/aWQ9ODEwNCZzdWI9MTA0JmM9diZ0dGY9dmFyaWFZS1zY3JpcHQucmVndWxhci50dGYmbj12YXJpYW5lLXNjcmlwdC1yZWd1bGFy/Variane Script Regular.ttf" rel="stylesheet" type="text/css"/>
    <style>
      body {
            background-color: #D5DFE5;
      }
    </style>
</head>
<%= render "devise/shared/navbar" %>

<%= form_with(model: sell_game, local: true) do |form| %>
  <% if sell_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sell_game.errors.count, "error") %> prohibited this sell_game from being saved:</h2>

      <ul>
        <% sell_game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= form.label :picture %><br />
      <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg', class:"form-control"%>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, class:"form-control"  %> 
  </div>


  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sell_games/_index.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://blogfonts.com/css/aWQ9ODEwNCZzdWI9MTA0JmM9diZ0dGY9dmFyaWFZS1zY3JpcHQucmVndWxhci50dGYmbj12YXJpYW5lLXNjcmlwdC1yZWd1bGFy/Variane Script Regular.ttf" rel="stylesheet" type="text/css"/>
    <style>
      body {
            background-color: #D5DFE5;
      }
    </style>
</head>
<%= render "devise/shared/navbar" %>

<body>
<hr class="new1">
    <% @sell_games.each do |sell_game| %>
    <div class="card">
      <td><%= image_tag sell_game.picture, class: "card-img-top" %> </td>

      <div class="card-body">
        <h5 class="card-title"><td><%= sell_game.title %></td></h5>
        <p class="card-text"><td><%= sell_game.description %></td></p>
        <td><%= link_to 'Show', sell_game, class:"btn btn-primary" %></td>

  </div>
  </div>
    <% end %>
    <br>
</div>
<br>
<hr class="new2">
<br>
<br>
<br>
</body>

app/views/sell_games/edit.html.erb
<h1>Editing Sell Game</h1>

<%= render 'form', sell_game: @sell_game %>

<%= link_to 'Show', @sell_game %> |
<%= link_to 'Back', sell_games_path %>

app/views/sell_games/index.html.erb
<p id="notice"><%= notice %></p>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://blogfonts.com/css/aWQ9ODEwNCZzdWI9MTA0JmM9diZ0dGY9dmFyaWFZS1zY3JpcHQucmVndWxhci50dGYmbj12YXJpYW5lLXNjcmlwdC1yZWd1bGFy/Variane Script Regular.ttf" rel="stylesheet" type="text/css"/>
    <style>
      body {
            background-color: #D5DFE5;
      }
    </style>
</head>
<%= render "devise/shared/navbar" %>

<body>
<h1 id="curh1">Current Listings</h1>
<%= link_to 'Post New Item', new_sell_game_path, id:"pni" %>
<br>
<hr class="new1">
    <% @sell_games.each do |sell_game| %>
    <div class="card">
      <td><%= image_tag sell_game.picture, class: "card-img-top" %> </td>

      <div class="card-body">
        <h5 class="card-title"><td><%= sell_game.title %></td></h5>
        <p class="card-text"><td><%= sell_game.description %></td></p>
        <td><%= link_to 'Show', sell_game, class:"btn btn-primary" %></td>

  </div>
  </div>
    <% end %>
    <br>
</div>
<br>
<hr class="new2">
<br>
<br>
<br>
</body>

app/views/sell_games/mygames.html.erb
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://blogfonts.com/css/aWQ9ODEwNCZzdWI9MTA0JmM9diZ0dGY9dmFyaWFZS1zY3JpcHQucmVndWxhci50dGYmbj12YXJpYW5lLXNjcmlwdC1yZWd1bGFy/Variane Script Regular.ttf" rel="stylesheet" type="text/css"/>
    <style>
      body {
            background-color: #D5DFE5;
      }
    </style>
</head>


<%= render "devise/shared/navbar" %>

<body>
<h1 id="curh1">My Listings</h1>
<%= link_to 'Post New Item', new_sell_game_path, id:"pni" %>
<br>
<hr class="new1">
  
    <% @sell_games.each do |sell_game| %>
    <div class="card">
      <td><%= image_tag sell_game.picture, class: "card-img-top" %> </td>

      <div class="card-body">
        <h5 class="card-title"><td><%= sell_game.title %></td></h5>
        <p class="card-text"><td><%= sell_game.description %></td></p>
        <td><%= link_to 'Show', sell_game, class:"btn btn-primary" %></td>
        <td><% if can? :update, sell_game %><%= link_to 'Edit', edit_sell_game_path(sell_game), class:"btn btn-primary" %> <% end %></td>
        <td><% if can? :destroy, sell_game %><%= link_to 'Destroy', sell_game, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %><% end %></td>


  </div>
  </div>
    <% end %>
    <br>
</div>
<br>
<hr class="new2">
<br>
<br>
<br>
</body>


<%= link_to 'Post New Item', new_sell_game_path %>
<%= link_to 'Home', root_path %>

app/views/sell_games/new.html.erb
<h1>New Listing</h1>
<hr class="new1">

<%= render 'form', sell_game: @sell_game %>

app/views/sell_games/search.erb
<h1> Search Results </h1>

<%= render 'sell_games/index' %>

app/views/sell_games/show.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://blogfonts.com/css/aWQ9ODEwNCZzdWI9MTA0JmM9diZ0dGY9dmFyaWFZS1zY3JpcHQucmVndWxhci50dGYmbj12YXJpYW5lLXNjcmlwdC1yZWd1bGFy/Variane Script Regular.ttf" rel="stylesheet" type="text/css"/>
    <style>
      body 
      {
            background-color: #D5DFE5;
      }
    </style>
</head>
<%= render "devise/shared/navbar" %>



<p id="notice"><%= notice %></p>

<%= image_tag @sell_game.picture, id:"showpic" %>
<div class="textcontainer2">
<p>
  <strong id="titles">Title:</strong>
  <%= @sell_game.title %>
</p>
</div>
<div class="textcontainer">
<p>
  <strong>Price:</strong>
  <%= @sell_game.price %>
</p>
</div>
<div class="textcontainer">
<p>
  <strong>Description:</strong>
  <%= @sell_game.description %>
</p>
</div>
<div class="textcontainer">
<p>
  <strong>User:</strong>
  <%= @sell_game.user.email %>
</p>
<br>
<p>
<button data-stripe="payment">Buy Game <%= number_to_currency(@sell_game.price) %></button>

<%= link_to 'Back', sell_games_path %>
<script src="https://js.stripe.com/v3/"></script>

<script>
    document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
        const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
        stripe.redirectToCheckout({
            sessionId: "<%= @session_id %>"
        });
    });
</script>
</p>

</div>

<% if can? :update, @sell_games %> <%= link_to 'Edit', edit_sell_game_path(@sell_game) %> | <% end %>